# Atlas specific settings
# left-hand side should be in JSON synthax
# int = 1
# float = 1.2
# bool = true/false (lower case)
# str = "string" (double qotes)
# list = [1, 2, 3]
# dict = {"a": 1, "b": 2} (key must be string)
# affine_atlas = "atlasForAffineRegistration.txt.gz"

[names]
affine_atlas = "affine_no_neck.txt.gz"
atlas_level1 = "atlas_level1.txt.gz"
atlas_level2 = "atlas_level2.txt.gz"
template_name = "template.nii.gz"
gaussian_parameters_T1 = "sharedGMMParameters.txt"
gaussian_parameters_T2 = "sharedGMMParameters.txt"
lookup_table_segmentation = "compressionLookupTable.txt"

[neck_optimization]
neck_tissues = [45, 47, 49, 50]

# This maps the labels in the segmentation to simnibs tissue labels
[conductivity_mapping]
simnibs_tissues = {"WM": 1,
                   "GM": 2,
                   "CSF": 3,
                   "Scalp": 5,
                   "Eyes": 6,
                   "Compact_bone": 7,
                   "Spongy_bone": 8,
                   "Blood": 9,
                   "Muscle": 10,
		   "Air_pockets": 11}

segmentation_tissues = {"WM": [41, 8, 6, 9, 7, 16, 18, 20, 19, 10, 21, 33, 34, 30, 40, 49, 55],
                        "GM": [1, 4, 5, 12, 14, 13, 15, 25, 26, 22, 24, 35, 36, 29, 32, 37, 2],
                        "CSF": [3, 38, 17, 11, 16, 10, 21, 23, 27, 31, 28, 39, 54],
                        "Scalp": [43, 44, 51, 42],
                        "Eyes": [53],
                        "Compact_bone": [47],
                        "Spongy_bone": [50],
                        "Blood": [46, 48],
                        "Muscle": [52],
			"Air_pockets": [45]}
